// AUTO-GENERATED from Balanced Body manual tables of contents
// Source: all apparatus manuals photographed by user

export type Apparatus =
  | 'Mat'
  | 'Mat with Props'
  | 'Reformer 1'
  | 'Reformer 2'
  | 'Reformer 3'
  | 'Trapeze Table'
  | 'Chair'
  | 'Step Barrel'
  | 'Ladder Barrel';

export interface ExerciseEntry {
  name: string;
  apparatus: Apparatus;
}

export const EXERCISE_LIST: ExerciseEntry[] = [

  // ─── MAT 1 ──────────────────────────────────────────────────────────────────
  { name: 'The Hundred Preparation', apparatus: 'Mat' },
  { name: 'The Hundred', apparatus: 'Mat' },
  { name: 'The Roll Up', apparatus: 'Mat' },
  { name: 'Single Leg Circles', apparatus: 'Mat' },
  { name: 'Rolling Like a Ball', apparatus: 'Mat' },
  { name: 'Single Leg Stretch', apparatus: 'Mat' },
  { name: 'Double Leg Stretch', apparatus: 'Mat' },
  { name: 'Single Straight Leg Stretch', apparatus: 'Mat' },
  { name: 'Double Straight Leg Stretch', apparatus: 'Mat' },
  { name: 'Criss Cross', apparatus: 'Mat' },
  { name: 'Spine Stretch Forward', apparatus: 'Mat' },
  { name: 'Spine Stretch Side', apparatus: 'Mat' },
  { name: 'Saw', apparatus: 'Mat' },
  { name: 'Open Leg Rocker', apparatus: 'Mat' },
  { name: 'Swan', apparatus: 'Mat' },
  { name: 'Single Leg Kicks', apparatus: 'Mat' },
  { name: 'Double Leg Kicks', apparatus: 'Mat' },
  { name: 'Swimming', apparatus: 'Mat' },
  { name: 'Side Leg Lifts', apparatus: 'Mat' },
  { name: 'Side Leg Circles Big & Small', apparatus: 'Mat' },
  { name: 'Side Leg Kicks', apparatus: 'Mat' },
  { name: 'Side Leg Bicycle', apparatus: 'Mat' },
  { name: 'Side Leg Bananas', apparatus: 'Mat' },
  { name: 'Seal', apparatus: 'Mat' },
  { name: 'Push Ups', apparatus: 'Mat' },

  // ─── MAT 3 (ADVANCED) ───────────────────────────────────────────────────────
  { name: 'Spine Twist', apparatus: 'Mat' },
  { name: 'Teaser Preparation', apparatus: 'Mat' },
  { name: 'Teaser 1 - Torso Roll Down', apparatus: 'Mat' },
  { name: 'Teaser 2 - Leg Lowers', apparatus: 'Mat' },
  { name: 'Teaser 3 - Arms and Legs Together', apparatus: 'Mat' },
  { name: 'Hip Circles', apparatus: 'Mat' },
  { name: 'Roll Over', apparatus: 'Mat' },
  { name: 'Modified Corkscrew', apparatus: 'Mat' },
  { name: 'Corkscrew', apparatus: 'Mat' },
  { name: 'Neck Pull', apparatus: 'Mat' },
  { name: 'Leg Pull Down', apparatus: 'Mat' },
  { name: 'Leg Pull Up', apparatus: 'Mat' },
  { name: 'Jackknife', apparatus: 'Mat' },
  { name: 'Kneeling Side Kicks', apparatus: 'Mat' },
  { name: 'Seated Twist', apparatus: 'Mat' },
  { name: 'Side Bend Twist', apparatus: 'Mat' },
  { name: 'Side Bend Mermaid', apparatus: 'Mat' },
  { name: 'Scissors', apparatus: 'Mat' },
  { name: 'Bicycle', apparatus: 'Mat' },
  { name: 'Shoulder Bridge', apparatus: 'Mat' },
  { name: 'Boomerang', apparatus: 'Mat' },
  { name: 'Swan Dive & Swan Rocking', apparatus: 'Mat' },
  { name: 'Rocking', apparatus: 'Mat' },

  // ─── MAT WITH PROPS ─────────────────────────────────────────────────────────
  { name: 'Core Warm Ups', apparatus: 'Mat with Props' },
  { name: 'The Hundred', apparatus: 'Mat with Props' },
  { name: 'Single Leg Stretch', apparatus: 'Mat with Props' },
  { name: 'Double Leg Stretch', apparatus: 'Mat with Props' },
  { name: 'Single Straight Leg Stretch', apparatus: 'Mat with Props' },
  { name: 'Double Straight Leg Stretch', apparatus: 'Mat with Props' },
  { name: 'Criss Cross', apparatus: 'Mat with Props' },
  { name: 'Roll Up', apparatus: 'Mat with Props' },
  { name: 'Rolling Like a Ball', apparatus: 'Mat with Props' },
  { name: 'Open Leg Rocker', apparatus: 'Mat with Props' },
  { name: 'Teaser', apparatus: 'Mat with Props' },
  { name: 'Swan', apparatus: 'Mat with Props' },
  { name: 'Swimming', apparatus: 'Mat with Props' },
  { name: 'Single Leg Kick', apparatus: 'Mat with Props' },
  { name: 'Double Leg Kick', apparatus: 'Mat with Props' },
  { name: 'Banana', apparatus: 'Mat with Props' },
  { name: 'Hip Mobility', apparatus: 'Mat with Props' },
  { name: 'Footwork', apparatus: 'Mat with Props' },
  { name: 'Hip Extensor Work', apparatus: 'Mat with Props' },
  { name: 'Side Lying Leg Work', apparatus: 'Mat with Props' },
  { name: 'Lower Body Power', apparatus: 'Mat with Props' },
  { name: 'Standing Leg Work', apparatus: 'Mat with Props' },
  { name: 'Glenohumeral Stability', apparatus: 'Mat with Props' },
  { name: 'Shoulder Mobility', apparatus: 'Mat with Props' },
  { name: 'Posterior Shoulder', apparatus: 'Mat with Props' },
  { name: 'Anterior Shoulder', apparatus: 'Mat with Props' },
  { name: 'Seated Arm Series', apparatus: 'Mat with Props' },

  // ─── REFORMER 1 ─────────────────────────────────────────────────────────────
  { name: 'Single Leg Footwork', apparatus: 'Reformer 1' },
  { name: 'Footwork on Footplate', apparatus: 'Reformer 1' },
  { name: 'Jumping on Footplate', apparatus: 'Reformer 1' },
  { name: 'Coordination', apparatus: 'Reformer 1' },
  { name: 'Short Spine Massage', apparatus: 'Reformer 1' },
  { name: 'Stomach Massage', apparatus: 'Reformer 1' },
  { name: 'Long Box Back Stroke', apparatus: 'Reformer 1' },
  { name: 'Long Box Breast Stroke', apparatus: 'Reformer 1' },
  { name: 'Long Box Swimming', apparatus: 'Reformer 1' },
  { name: 'Short Box Oblique Abdominals', apparatus: 'Reformer 1' },
  { name: 'Short Box Advanced Abdominals', apparatus: 'Reformer 1' },
  { name: 'Short Box Mermaid', apparatus: 'Reformer 1' },
  { name: 'Short Box Climb a Tree', apparatus: 'Reformer 1' },
  { name: 'Knee Stretch Knees Off - Jackrabbit', apparatus: 'Reformer 1' },
  { name: 'Arabesque & Single Leg Elephant', apparatus: 'Reformer 1' },
  { name: 'Down Stretch', apparatus: 'Reformer 1' },
  { name: 'Semi Circle', apparatus: 'Reformer 1' },
  { name: 'Chest Expansion', apparatus: 'Reformer 1' },
  { name: 'Kneeling Side Arms', apparatus: 'Reformer 1' },
  { name: 'Rowing Front I - Sitting Tall', apparatus: 'Reformer 1' },
  { name: 'Rowing Front II - Bending Down', apparatus: 'Reformer 1' },
  { name: 'Corkscrew', apparatus: 'Reformer 1' },

  // ─── REFORMER 2 ─────────────────────────────────────────────────────────────
  { name: 'Footwork', apparatus: 'Reformer 2' },
  { name: 'Roll Down', apparatus: 'Reformer 2' },
  { name: 'Supine Arm Work', apparatus: 'Reformer 2' },
  { name: 'The Hundred', apparatus: 'Reformer 2' },
  { name: 'Kneeling Abdominals Facing Back', apparatus: 'Reformer 2' },
  { name: 'Kneeling Abdominals Facing Front', apparatus: 'Reformer 2' },
  { name: 'Feet in Straps', apparatus: 'Reformer 2' },
  { name: 'Long Box Pulling Straps', apparatus: 'Reformer 2' },
  { name: 'Long Box Overhead Press & Swan', apparatus: 'Reformer 2' },
  { name: 'Short Box Abdominals', apparatus: 'Reformer 2' },
  { name: 'Bridging & Pelvic Lift', apparatus: 'Reformer 2' },
  { name: 'Knee Stretch', apparatus: 'Reformer 2' },
  { name: 'Elephant', apparatus: 'Reformer 2' },
  { name: 'Long Stretch', apparatus: 'Reformer 2' },
  { name: 'Up Stretch', apparatus: 'Reformer 2' },
  { name: 'Arm Work Facing Straps', apparatus: 'Reformer 2' },
  { name: 'Arm Work Facing Footbar', apparatus: 'Reformer 2' },
  { name: 'Standing/Side Splits', apparatus: 'Reformer 2' },
  { name: 'Lunges', apparatus: 'Reformer 2' },
  { name: 'Side Stretch/Mermaid', apparatus: 'Reformer 2' },
  { name: 'Cleopatra', apparatus: 'Reformer 2' },

  // ─── REFORMER 3 ─────────────────────────────────────────────────────────────
  { name: 'Long Box Double Leg Kick', apparatus: 'Reformer 3' },
  { name: 'Long Box Teaser', apparatus: 'Reformer 3' },
  { name: 'Long Box Horseback', apparatus: 'Reformer 3' },
  { name: 'Long Box Swan', apparatus: 'Reformer 3' },
  { name: 'Long Box Grasshopper', apparatus: 'Reformer 3' },
  { name: 'Long Box Rocking', apparatus: 'Reformer 3' },
  { name: 'Rowing Back I Round Back', apparatus: 'Reformer 3' },
  { name: 'Rowing Back II Flat Back', apparatus: 'Reformer 3' },
  { name: 'Reverse Abdominals', apparatus: 'Reformer 3' },
  { name: 'Long Spine Massage', apparatus: 'Reformer 3' },
  { name: 'Jackknife', apparatus: 'Reformer 3' },
  { name: 'Thigh Stretch', apparatus: 'Reformer 3' },
  { name: 'Tendon Stretch', apparatus: 'Reformer 3' },
  { name: 'Long Back Stretch (Slide)', apparatus: 'Reformer 3' },
  { name: 'Snake', apparatus: 'Reformer 3' },
  { name: 'Twist', apparatus: 'Reformer 3' },
  { name: 'Control Front Facing Carriage', apparatus: 'Reformer 3' },
  { name: 'Control Back Facing Ceiling', apparatus: 'Reformer 3' },
  { name: 'Star/Side Support', apparatus: 'Reformer 3' },
  { name: 'Splits', apparatus: 'Reformer 3' },

  // ─── TRAPEZE TABLE ──────────────────────────────────────────────────────────
  { name: 'Upper Arms', apparatus: 'Trapeze Table' },
  { name: 'Roll Down', apparatus: 'Trapeze Table' },
  { name: 'Assisted Sit Ups', apparatus: 'Trapeze Table' },
  { name: 'Advanced Sit Ups', apparatus: 'Trapeze Table' },
  { name: 'Leg Springs Supine Pull', apparatus: 'Trapeze Table' },
  { name: 'Leg Springs Side Lying', apparatus: 'Trapeze Table' },
  { name: 'Footwork - Bend and Stretch', apparatus: 'Trapeze Table' },
  { name: 'Footwork - Dorsiflexion', apparatus: 'Trapeze Table' },
  { name: 'Push Through Seated Front', apparatus: 'Trapeze Table' },
  { name: 'Circle Saw', apparatus: 'Trapeze Table' },
  { name: 'Cat Sitting', apparatus: 'Trapeze Table' },
  { name: 'Cat Kneeling', apparatus: 'Trapeze Table' },
  { name: 'Pull Downs - Double Arms', apparatus: 'Trapeze Table' },
  { name: 'Pull Downs - Single Arm', apparatus: 'Trapeze Table' },
  { name: 'Scapula Glides', apparatus: 'Trapeze Table' },
  { name: 'Spread Eagle', apparatus: 'Trapeze Table' },
  { name: "Joe's Breathing", apparatus: 'Trapeze Table' },
  { name: "Carola's Breathing", apparatus: 'Trapeze Table' },
  { name: 'The Hundred', apparatus: 'Trapeze Table' },
  { name: 'Leg Springs - Standing', apparatus: 'Trapeze Table' },
  { name: 'Leg Springs Supine - Hip Flexor Pull', apparatus: 'Trapeze Table' },
  { name: 'Swan - Push Through Bar', apparatus: 'Trapeze Table' },
  { name: 'Advanced Swan - Push Through Bar', apparatus: 'Trapeze Table' },
  { name: 'Swan - Roll Down Bar', apparatus: 'Trapeze Table' },
  { name: 'Flying Eagle/Double Leg Kick', apparatus: 'Trapeze Table' },
  { name: 'Supine Arm Circles', apparatus: 'Trapeze Table' },
  { name: 'Prone Arm Circles', apparatus: 'Trapeze Table' },
  { name: 'Rowing Front - Sitting Tall', apparatus: 'Trapeze Table' },
  { name: 'Rowing Front - Bending Down', apparatus: 'Trapeze Table' },
  { name: 'Rowing Back - Round Back', apparatus: 'Trapeze Table' },
  { name: 'Rowing Back - Flat Back', apparatus: 'Trapeze Table' },
  { name: 'Teaser Top Sprung', apparatus: 'Trapeze Table' },
  { name: 'Teaser Bottom Sprung', apparatus: 'Trapeze Table' },
  { name: 'Standing Arms - Facing Away', apparatus: 'Trapeze Table' },
  { name: 'Standing Arms - Facing the Table', apparatus: 'Trapeze Table' },
  { name: 'Standing Arms - Facing the Side', apparatus: 'Trapeze Table' },
  { name: 'Tower', apparatus: 'Trapeze Table' },
  { name: 'Monkey', apparatus: 'Trapeze Table' },
  { name: 'Short Spine/Semi Circle/Ferris Wheel', apparatus: 'Trapeze Table' },
  { name: 'Leg Springs Supine - Magician', apparatus: 'Trapeze Table' },
  { name: 'Leg Springs Supine - Dolphin', apparatus: 'Trapeze Table' },
  { name: 'Airplane', apparatus: 'Trapeze Table' },
  { name: 'Push Through Back', apparatus: 'Trapeze Table' },
  { name: 'Mermaid Sitting', apparatus: 'Trapeze Table' },
  { name: 'Mermaid Advanced', apparatus: 'Trapeze Table' },
  { name: 'Side Bends', apparatus: 'Trapeze Table' },
  { name: 'Parakeet', apparatus: 'Trapeze Table' },
  { name: 'Bridging', apparatus: 'Trapeze Table' },
  { name: 'Chest Expansion/Thigh Stretch', apparatus: 'Trapeze Table' },
  { name: 'Rolling In and Out', apparatus: 'Trapeze Table' },
  { name: 'Hanging Pull Ups', apparatus: 'Trapeze Table' },
  { name: 'Hanging Down', apparatus: 'Trapeze Table' },
  { name: 'Cat Walkover', apparatus: 'Trapeze Table' },

  // ─── CHAIR ──────────────────────────────────────────────────────────────────
  { name: 'Hamstring Stretch 1', apparatus: 'Chair' },
  { name: 'Hamstring Stretch 2', apparatus: 'Chair' },
  { name: 'One Arm Push-Up Standing', apparatus: 'Chair' },
  { name: 'Spine Stretch', apparatus: 'Chair' },
  { name: 'Double Leg Pumps', apparatus: 'Chair' },
  { name: 'Single Leg Pumps', apparatus: 'Chair' },
  { name: 'Standing Leg Pumps', apparatus: 'Chair' },
  { name: 'Achilles Stretch', apparatus: 'Chair' },
  { name: 'Leg Pumps Supine/Bridging', apparatus: 'Chair' },
  { name: 'Frogs Supine', apparatus: 'Chair' },
  { name: 'Scapula Mobilization', apparatus: 'Chair' },
  { name: 'Chest Press', apparatus: 'Chair' },
  { name: 'Side Body Twist/Side Lying Obliques', apparatus: 'Chair' },
  { name: 'Sitting Triceps Press', apparatus: 'Chair' },
  { name: 'Teaser on Floor', apparatus: 'Chair' },
  { name: 'Kneeling Mermaid', apparatus: 'Chair' },
  { name: 'Seated Mermaid', apparatus: 'Chair' },
  { name: 'Cat', apparatus: 'Chair' },
  { name: 'Lunges', apparatus: 'Chair' },
  { name: 'Plié Front and Back', apparatus: 'Chair' },
  { name: 'Frogs Standing', apparatus: 'Chair' },
  { name: 'Pull Up/Hamstring 3', apparatus: 'Chair' },
  { name: 'Reverse Swan/Torso Press Sit', apparatus: 'Chair' },
  { name: 'Reverse Swan/Side Arm Twist', apparatus: 'Chair' },
  { name: 'Triceps Sit', apparatus: 'Chair' },
  { name: 'Swan from Floor', apparatus: 'Chair' },
  { name: 'Swan on Seat', apparatus: 'Chair' },
  { name: 'Jackknife', apparatus: 'Chair' },
  { name: 'Corkscrew', apparatus: 'Chair' },
  { name: 'Press Up with Handles - Facing the Chair', apparatus: 'Chair' },
  { name: 'Press Up with Handles - Facing Away', apparatus: 'Chair' },
  { name: 'One Arm Push-Ups', apparatus: 'Chair' },
  { name: 'Handstand', apparatus: 'Chair' },
  { name: 'Tendon Stretch', apparatus: 'Chair' },
  { name: 'Step Downs', apparatus: 'Chair' },

  // ─── STEP BARREL ────────────────────────────────────────────────────────────
  { name: 'Lip Abdominals Series', apparatus: 'Step Barrel' },
  { name: 'Well Abdominal Series', apparatus: 'Step Barrel' },
  { name: 'Reach', apparatus: 'Step Barrel' },
  { name: 'Teaser - Forward & Reverse', apparatus: 'Step Barrel' },
  { name: 'Side Stretch/Side Sit Ups', apparatus: 'Step Barrel' },
  { name: 'Hip Mobility Series', apparatus: 'Step Barrel' },
  { name: 'Rolling In & Out', apparatus: 'Step Barrel' },
  { name: 'Roll Over/Overhead Stretch', apparatus: 'Step Barrel' },
  { name: 'Corkscrew', apparatus: 'Step Barrel' },
  { name: 'Low Bridge', apparatus: 'Step Barrel' },
  { name: 'Back Arch and Bridge', apparatus: 'Step Barrel' },
  { name: 'Swimming', apparatus: 'Step Barrel' },
  { name: 'Swan', apparatus: 'Step Barrel' },
  { name: 'Grasshopper', apparatus: 'Step Barrel' },

  // ─── LADDER BARREL ──────────────────────────────────────────────────────────
  { name: 'Ladder Barrel Stretches', apparatus: 'Ladder Barrel' },
  { name: 'Swan Dive', apparatus: 'Ladder Barrel' },
  { name: 'Leg Lifts/Grasshopper', apparatus: 'Ladder Barrel' },
  { name: 'Short Box Abdominal Series', apparatus: 'Ladder Barrel' },
  { name: 'Climb a Tree', apparatus: 'Ladder Barrel' },
  { name: 'Side Sit Up', apparatus: 'Ladder Barrel' },
  { name: 'Horseback', apparatus: 'Ladder Barrel' },
  { name: 'Lay Backs', apparatus: 'Ladder Barrel' },
];

// Grouped by apparatus for dropdowns
export const EXERCISES_BY_APPARATUS: Record<Apparatus, string[]> = Object.fromEntries(
  (Object.keys({
    'Mat': [], 'Mat with Props': [], 'Reformer 1': [], 'Reformer 2': [],
    'Reformer 3': [], 'Trapeze Table': [], 'Chair': [], 'Step Barrel': [], 'Ladder Barrel': []
  }) as Apparatus[]).map(apparatus => [
    apparatus,
    EXERCISE_LIST.filter(e => e.apparatus === apparatus).map(e => e.name)
  ])
) as Record<Apparatus, string[]>;

// Muscle groups for the Learn screen dropdown
export const MUSCLE_GROUPS = [
  'Abdominals',
  'Transverse Abdominis (TVA)',
  'Obliques',
  'Rectus Abdominis',
  'Spinal Extensors',
  'Erector Spinae',
  'Multifidus',
  'Hip Flexors',
  'Psoas',
  'Glutes',
  'Hamstrings',
  'Quadriceps',
  'Adductors',
  'Hip Rotators',
  'Shoulder Stabilizers',
  'Rotator Cuff',
  'Scapular Stabilizers',
  'Latissimus Dorsi',
  'Chest / Pectorals',
  'Triceps',
  'Biceps',
  'Calves / Gastrocnemius',
  'Tibialis Anterior',
  'Deep Neck Flexors',
  'Diaphragm',
];
